
mpls_311:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account # Comment out for automated running
      dataset: mpls_311_development
      threads: 4
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS')}}" # Comment out for automated running
    prod:
      type: bigquery
      method: service-account # Comment out for automated running
      dataset: mpls_311_production
      threads: 4
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS')}}" # Comment out for automated running