
mpls_311:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      dataset: mpls_311_development
      threads: 4
      # keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS')}}"
    prod:
      type: bigquery
      method: service-account
      dataset: mpls_311_production
      threads: 4
      # keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS')}}"